#!/bin/bash

pdfGrayscale(){
  gs \
   -sDEVICE=pdfwrite \
   -sProcessColorModel=DeviceGray \
   -sColorConversionStrategy=Gray \
   -dOverrideICC \
   -o "$2" \
   -f "$1"
}

spaceAnalize(){
  sudo du -cksh * | sort -h
}

ecmd() {
    vim $HOME/.bashfiles/personaCommands
}

reload(){
    source $HOME/.bashrc
}

compileGcloudImage(){
  tagName=gcr.io/${PROJECTID}/$(basename `pwd`)
  docker tag $(basename `pwd`) $tagName
  docker push $tagName
}

deployProduction(){
  gcloud app deploy app_production.yaml
}

runPsql(){
  psql -U postgres
}
