#!/bin/bash

spaceAnalize(){
  sudo du -cksh * | sort -h
}

ecmd() {
    vim $HOME/.bashfiles/personaCommands
}

runDockerApp(){
  APP_NAME=$(basename $PWD)
  docker-compose up -d
  docker attach "${APP_NAME}-app-1"
}

reload(){
    source $HOME/.bashrc
}
